### ISSUE TITLE
What should I do with Everforest-Dark-B-Gnome42.zip ?

### ISSUE THREAD

**Issue by ForteDexe** [Fausto-Korpsvart/Everforest-GTK-Theme#1]
Hello, thank you for your amazing work, I loved it.
But the file gtk-Everforest-Dark-B.css quite confuses me, and I dont know what should I do with it (Iam using gnome 42).

**Comment by Fausto-Korpsvart** [comment]
> 

Hi, @ForteDexe, well, the file for Gnome 42 should be placed in the path: '~/config/gtk-4.0/' and you should rename it to just 'gtk.css', this applies the theme automatically, if you have an application open just close it and reopen it and the theme will be applied, for GTK3 themes you need to apply them from Tweaks.

Sorry if it's too confusing at the moment, I haven't had much time to update the README and the description in Gnome Look, but I'll try to do it soon to avoid confusion, thanks for the support. };-]
