### ISSUE TITLE
Annoying bug in quick setting menu when using this theme as a shell theme

### ISSUE THREAD

**Issue by NoahStoessel** [Fausto-Korpsvart/Everforest-GTK-Theme#10]
OS: Fedora 38 Worksation
Same thing on OpenSuse tumbleweed in VirtualBox
Always happens cant seem to fix it

<img width="352" alt="New Screen Shot Name 2024-02-23 at 12 57 39 PM" src="https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/assets/101427997/ee08628d-282b-4851-87c8-908d9e258f09">

**Comment by scotabroad** [comment]
To my understanding, this is because the theme does not yet support changes from Gnome 45, which is an [open issue](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/issues/8)

**Comment by Fausto-Korpsvart** [comment]
> To my understanding, this is because the theme does not yet support changes from Gnome 45, which is an [open issue](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/issues/8)

@scotabroad, @NoahStoessel, yes, it is for that reason, but I am already working on the update that I will do soon.

**Comment by NoahStoessel** [comment]
> > To my understanding, this is because the theme does not yet support changes from Gnome 45, which is an [open issue](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/issues/8)
> 
> 
> 
> @scotabroad, @NoahStoessel, yes, it is for that reason, but I am already working on the update that I will do soon.

Great, thank you for the help, anyways love the theme, it looks great
