### ISSUE TITLE
Borders under Program Edges

### ISSUE THREAD

**Issue by Tripp1e** [Fausto-Korpsvart/Everforest-GTK-Theme#12]
I am using GNOME 46 and while I know it currently isnt supported, this is the only thing that really annoys me, so is there a quick fix? I don't have any knowledge of how theming actually works and if this is a rather annoying request, I can understand.

![image](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/assets/102437240/ec1ceea2-247e-460e-aa57-d8df1a8e38f6)
![image](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/assets/102437240/69636302-0f5e-4f61-93a8-98c168c81660)

I could try and do it myself if you could point me in the right direction.

**Comment by Fausto-Korpsvart** [comment]
> I am using GNOME 46 and while I know it currently isnt supported, this is the only thing that really annoys me, so is there a quick fix? I don't have any knowledge of how theming actually works and if this is a rather annoying request, I can understand.
> 
> ![image](https://private-user-images.githubusercontent.com/102437240/329356361-ec1ceea2-247e-460e-aa57-d8df1a8e38f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTA1NTUsIm5iZiI6MTcxNTYxMDI1NSwicGF0aCI6Ii8xMDI0MzcyNDAvMzI5MzU2MzYxLWVjMWNlZWEyLTI0N2UtNDYwZS1hYTU3LWQ4ZGYxYThlMzhmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxNDI0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjkwMWIyMjE4YjY4ZTNmYmYzZThiYzFhYTcyOTc5OGE2OTYyNjM2MGI2YTFmZDM1NWY0NTM1MWMyOTYyYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A3HATpXQAhT_mUvGaq-EOmUJfeNFXVTsk30EW4mF2dM) ![image](https://private-user-images.githubusercontent.com/102437240/329356909-69636302-0f5e-4f61-93a8-98c168c81660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTA1NTUsIm5iZiI6MTcxNTYxMDI1NSwicGF0aCI6Ii8xMDI0MzcyNDAvMzI5MzU2OTA5LTY5NjM2MzAyLTBmNWUtNGY2MS05M2E4LTk4YzE2OGM4MTY2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxNDI0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmYzZDFjZjFhYmRkMzkxZWZkMjgyNTJmMDBhNTQ0MGU0MDhlZDY5YThmYTk0NWY0NDU4NmM3NWU0ZWJlMmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IXCl32P4oO271x8d35Z3zN2_yq63DXtTzBBlKD5e5Ns)
> 
> I could try and do it myself if you could point me in the right direction.

Hello, @Tripp1e.

This theme has not been updated yet, I am working to update all the themes gradually, I will update this and the other remaining themes as soon as possible.
