### ISSUE TITLE
Memory bomb using this icon pack

### ISSUE THREAD

**Issue by whelpy** [Fausto-Korpsvart/Everforest-GTK-Theme#13]
When I apply this icon pack in cinnamon, and have telegram running, all 32GB of RAM suddenly gets consumed, then PC freezes.
Only the icon pack, other parts give no issues.

Another (related?) problem with the icon pack - downloaded zip achieve with icons cannot be open in mc, it freezes.

**Comment by Fausto-Korpsvart** [comment]
> When I apply this icon pack in cinnamon, and have telegram running, all 32GB of RAM suddenly gets consumed, then PC freezes. Only the icon pack, other parts give no issues.
> 
> Another (related?) problem with the icon pack - downloaded zip achieve with icons cannot be open in mc, it freezes.

Actually this icon pack is generated by an application, the icons are not my creation, I just generated the icons to match the colours of the GTK theme.
But you can use any kind of icons, in Gnome Look you can find a lot of cool icon packs.
