### ISSUE TITLE
arrow buttons in main menu are overlapping

### ISSUE THREAD

**Issue by Yohh** [Fausto-Korpsvart/Everforest-GTK-Theme#18]
hi, thanks for this beautiful theme

the arrow buttons in the top-right main menu are overlapping, making it hard to use it
![Screenshot from 2024-08-05 14-36-53](https://github.com/user-attachments/assets/9a7310c7-756a-4189-9cbb-224fc68b8c16)

nixos unstable 24.11, the only other gnome extension used is vitals

**Comment by Fausto-Korpsvart** [comment]
> the arrow buttons in the top-right main menu are overlapping, making it hard to use it

Hi, @Yohh.

What version of GNOME does NIXOS Unstable use?
I think it's an old version of GNOME or maybe the repository you installed the theme from is also old.

Could you install the theme from this repository and check that it is working fine?

This is what the theme installed from this repository looks like.
![g_shell](https://github.com/user-attachments/assets/f3b5e537-1958-4bae-abf1-cd5551396f83)

**Comment by Yohh** [comment]
`gnome-shell --version` return `GNOME Shell 46.3.1`
and here is my home-manager config to install the theme:
![image](https://github.com/user-attachments/assets/dd6bd6e1-12f2-4a07-a6fb-59914457fc69)

**Comment by Yohh** [comment]
the nixos package manager ping to this github, you can see it at https://search.nixos.org/packages?channel=unstable&show=everforest-gtk-theme&from=0&size=200&sort=relevance&type=packages&query=everforest by clicking on the `homepage` button

**Comment by jn-sena** [comment]
Sorry for the inconvenience. I'm the maintainer of the `everforest-gtk-theme` package at nixpkgs, and I wasn't available for a while so the package is quite old at this point. I'll hopefully make a pull request in a day or so, it should therefore land in the `nixos-unstable` in 1-2 weeks.

**Comment by Yohh** [comment]
ok no problem, I'll wait

thanks!

**Comment by Fausto-Korpsvart** [comment]
> `gnome-shell --version` returns `GNOME Shell 46.3.1` and here is my home-manager config to install the theme:
> edit: I just added dash-to-panel, the issue still remains without

This is not caused by another extension and, in the version of GNOME you are using, the theme should work correctly.

My recommendation is to install the theme from this repository or from Pling, as it is up-to-date and works correctly with the version of GNOME you are using.

**Comment by Yohh** [comment]
yes I'll wait, it's not that inconvenient
