### ISSUE TITLE
Inconsistent naming of the icon themes

### ISSUE THREAD

**Issue by jn-sena** [Fausto-Korpsvart/Everforest-GTK-Theme#19]
I just noticed it while writing the Nix derivation, the names of the icon theme folders are

- `Everforest-Dark`,
- and `everforest_light`,

which could pose a problem in the future. I'd be glad if you looked at it as well.

**Comment by Fausto-Korpsvart** [comment]
> I just noticed it while writing the Nix derivation, the names of the icon theme folders are
> 
> * `Everforest-Dark`,
> * and `everforest_light`,
> 
> which could pose a problem in the future. I'd be glad if you looked at it as well.

Sure, I'll check and change it, thanks }:]

**Comment by Fausto-Korpsvart** [comment]
@jn-sena, It is done }:]
