### ISSUE TITLE
need help with start menu!

### ISSUE THREAD

**Issue by claws3301** [Fausto-Korpsvart/Everforest-GTK-Theme#20]
![black_border](https://github.com/user-attachments/assets/2416b580-e2c1-471f-9288-c438e3c01196)
![border-2](https://github.com/user-attachments/assets/7e9c4f15-1805-4415-a0d0-66b5ccbf99a8)
I use Xfce desktop in linux mint 21.1
everything is almost perfect but I found there's a black border under the start menu
I tried metacity and xfwm, it always exists. Restarting also can't fix it.

Love this theme so please help

**Comment by Fausto-Korpsvart** [comment]
In the `Settings`, go to the `Window Manager Tweaks` option and, in the `Compositor` tab, you must enable display compositing

![XFCE-Compositor](https://github.com/user-attachments/assets/deb0cafa-f452-4311-8b30-af44ac17d87b)

**Comment by claws3301** [comment]
> In the `Settings`, go to the `Window Manager Tweaks` option and, in the `Compositor` tab, you must enable display compositing
> 
> ![XFCE-Compositor](https://private-user-images.githubusercontent.com/47998118/357148831-deb0cafa-f452-4311-8b30-af44ac17d87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODg1MTMsIm5iZiI6MTcyMzQ4ODIxMywicGF0aCI6Ii80Nzk5ODExOC8zNTcxNDg4MzEtZGViMGNhZmEtZjQ1Mi00MzExLThiMzAtYWY0NGFjMTdkODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE4NDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZjFmNGI4OWNhYWQwNWNhMDcyYjRmYjYwMDk3MzI3ZDJiOGZiODdjOWU4YWY4ZjhjNmRkMjM3ZDEzN2VjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HJvj2Nmua4_tJB-b3W3_QwIqcdUyQYZlR0S31s22WIU)

Thanks for replying! 
My Compositor is enabled, the border is still there.

**Comment by Fausto-Korpsvart** [comment]
> Thanks for replying! My Compositor is enabled, the border is still there.

Sorry for the late reply; well, you can check the transparency within the menu settings, setting the transparency to 95 or 99 solves that annoying problem.
