### ISSUE TITLE
Applying gtk4 theme makes gnome-settings ends up buggy.

### ISSUE THREAD

**Issue by foolishprogrammer** [Fausto-Korpsvart/Everforest-GTK-Theme#3]
Does not matter what version i use, after i copy the gtk.css to gtk-4.0, gnome settings ends up really slow, i can see stutter when moving the window, and switching between full screen and windowed always have some artifact.
![Screenshot from 2022-10-31 12-06-28](https://user-images.githubusercontent.com/39590364/198936616-baae7a88-e72d-4805-bd7b-4fd8b7f2efab.png)

**Comment by Fausto-Korpsvart** [comment]
> Does not matter what version i use, after i copy the gtk.css to gtk-4.0, gnome settings ends up really slow, i can see stutter when moving the window, and switching between full screen and windowed always have some artifact. ![Screenshot from 2022-10-31 12-06-28](https://user-images.githubusercontent.com/39590364/198936616-baae7a88-e72d-4805-bd7b-4fd8b7f2efab.png)

What distro and version of GNOME are you using?
Because I'm testing all themes on Fedora 36, Fedora 37, Ubuntu 22.04, PopOS 22.3, Manjaro 21.3, and I don't see any error, I'm not able to reproduce the problem, everything works fine.

**Comment by foolishprogrammer** [comment]
I'm using endeavor os gnome 42.4 on X11. I wish i can use wayland, but my laptop have nvidia 1050, so it might be related to that?
