### ISSUE TITLE
no scroll bar in playlist in Audacious

### ISSUE THREAD

**Issue by tro-oper** [Fausto-Korpsvart/Everforest-GTK-Theme#5]
audacious has no scroll bar in playlist with this theme, also tokyonight

observed both in gnome 43 and LXDE

audacious 4.3 on Arch, gtk version from AUR

**Comment by Fausto-Korpsvart** [comment]
Thank you for reporting, and sorry for responding so late.
I will check and fix as soon as I have some free time, unfortunately work hasn't left me much time lately.
