### ISSUE TITLE
GNOME 45 - Support?

### ISSUE THREAD

**Issue by Skydeke** [Fausto-Korpsvart/Everforest-GTK-Theme#8]
Hey @Fausto-Korpsvart,
I love this theme and would love to use on Gnome 45. I know from [here](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/43) that you are pretty busy updating your themes, but I hope that you can find the time to update this theme too. 
For example the Quick-Settings menu changed and some of the options are behind other buttons.
![image](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/assets/26024467/d0d40056-13a0-45ce-89e9-e4cda57ba577)

Thank you very much for maintaining this theme.

**Comment by Fausto-Korpsvart** [comment]
> Hey @Fausto-Korpsvart, I love this theme and would love to use on Gnome 45. I know from [here](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/43) that you are pretty busy updating your themes, but I hope that you can find the time to update this theme too. For example the Quick-Settings menu changed and some of the options are behind other buttons. ![image](https://user-images.githubusercontent.com/26024467/279771357-d0d40056-13a0-45ce-89e9-e4cda57ba577.png)
> 
> Thank you very much for maintaining this theme.

Yes, there will be update for G45, I am still working on this, I will update as soon as possible.

**Comment by Abhiranjan0001** [comment]
So is there any update ?

**Comment by Fausto-Korpsvart** [comment]
> So is there any update ?

I'm working on it, I've already updated Tokyonight and Gruvbox, this week I hope to update some more themes if work allows me.

Thanks for your support and patience.
