### ISSUE TITLE
Chromium decorators are not rendered well

### ISSUE THREAD

**Issue by Frusadev** [Fausto-Korpsvart/Everforest-GTK-Theme#9]
I just installed everforest, but there is a problem with chromium based browsers. Here's just a screenshot from chrome: 

![Screenshot 2023-11-02 22:15:35](https://github.com/Fausto-Korpsvart/Everforest-GTK-Theme/assets/81917636/f1535e2c-1879-4c8b-93da-1f707a1ede7b)

I've visited the gruvbox github, and it seems like other people are having the same problem.

**Information:**

OS: Arch Linux
Kernel: 6.5.9-arch2-1
WM: Openbox
Theme: Everforest-Dark-BL [GTK2/3]
CPU: AMD E1-1200 APU (2) @ 1.400GHz
GPU: AMD ATI Radeon HD 7310

**Comment by Fausto-Korpsvart** [comment]
> I just installed everforest, but there is a problem with chromium based browsers. Here's just a screenshot from chrome:
> 
> ![Screenshot 2023-11-02 22:15:35](https://user-images.githubusercontent.com/81917636/280140616-f1535e2c-1879-4c8b-93da-1f707a1ede7b.png)
> 
> I've visited the gruvbox github, and it seems like other people are having the same problem.
> 
> **Information:**
> 
> OS: Arch Linux Kernel: 6.5.9-arch2-1 WM: Openbox Theme: Everforest-Dark-BL [GTK2/3] CPU: AMD E1-1200 APU (2) @ 1.400GHz GPU: AMD ATI Radeon HD 7310

Thank you for reporting, @Frusadev, I am currently working on theme updates and will be looking to review this to fix any bugs.
